version: '3.4'

x-consul-base: &consul-base
  image: consul:latest
  command: "agent -data-dir /consul/config"

services:
  consul-dc1-agent-1:
    <<: *consul-base
    hostname: consul-dc1-agent-1
    volumes:
      - ./consul_client/config/consul-agent-1/config.json:/consul/config/config.json
    networks:
      consul-dc1: {}

  consul-dc1-agent-2:
    <<: *consul-base
    hostname: consul-dc1-agent-2
    volumes:
      - ./consul_client/config/consul-agent-2/config.json:/consul/config/config.json
    networks:
      consul-dc1: {}

  # consul-dc2-agent-1:
  #   <<: *consul-base
  #   hostname: consul-dc2-agent-1
  #   volumes:
  #     - ./consul_client/config/consul-dc2-agent-1/config.json:/consul/config/config.json
  #   networks:
  #     consul-dc2: {}

  # consul-dc3-agent-1:
  #   <<: *consul-base
  #   hostname: consul-dc3-agent-1
  #   volumes:
  #     - ./consul_client/config/consul-dc3-agent-1/config.json:/consul/config/config.json
  #   networks:
  #     consul-dc3: {}

  consul-dc1-server-1:
    <<: *consul-base
    hostname: consul-dc1-server-1
    volumes:
      - ./consul_server/config/consul-dc1-server-1/config.json:/consul/config/config.json
    networks:
      consul-dc1:
        ipv4_address: 172.16.0.11

  consul-dc1-server-2:
    <<: *consul-base
    hostname: consul-dc1-server-2
    volumes:
      - ./consul_server/config/consul-dc1-server-2/config.json:/consul/config/config.json
    networks:
      consul-dc1:
        ipv4_address: 172.16.0.12

  consul-dc1-server-3:
    <<: *consul-base
    hostname: consul-dc1-server-3
    ports:
      - "18400:8400"
      - "18500:8500"
      - "18600:8600"
      - "18600:8600/udp"
    volumes:
    - ./consul_server/config/consul-dc1-server-3/config.json:/consul/config/config.json
    networks:
      consul-dc1:
        ipv4_address: 172.16.0.13

networks:
  consul-dc1:
    ipam:
      config:
        - subnet: 172.16.0.0/24
  consul-dc2:
    ipam:
      config:
        - subnet: 172.16.1.0/24
  consul-dc3:
    ipam:
      config:
        - subnet: 172.16.2.0/24