version: '3.4'

x-consul-base: &consul-base
  image: consul:latest
  command: "agent -config-dir /consul/config"
  env_file:
    - ./config/env/consul-cli.env

services:
  consul-dc1-agent-1:
    <<: *consul-base
    hostname: consul-dc1-agent-1
    volumes:
      - ./config/acl/acl.json:/consul/config/acl.json
      - ./config/consul/checks.json:/consul/config/checks.json
      - ./config/consul/client_tls.json:/consul/config/tls.json
      - ./config/ssl/ca.pem:/etc/ssl/certs/consul-ca.pem
      - ./target_config/consul-dc1-agent-1/config.json:/consul/config/config.json
      - ./target_certs/consul-dc1-agent-1/client.pem:/etc/ssl/certs/client.pem
      - ./target_certs/consul-dc1-agent-1/client-key.pem:/home/consul/ssl/private/client-key.pem
      - ./target_certs/consul-dc1/cli.pem:/etc/ssl/certs/cli.pem
      - ./target_certs/consul-dc1/cli-key.pem:/home/consul/ssl/private/cli-key.pem
    networks:
      consul-poc: {}

  consul-dc1-agent-2:
    <<: *consul-base
    hostname: consul-dc1-agent-2
    volumes:
      - ./config/acl/acl.json:/consul/config/acl.json
      - ./config/consul/checks.json:/consul/config/checks.json
      - ./config/consul/client_tls.json:/consul/config/tls.json
      - ./config/ssl/ca.pem:/etc/ssl/certs/consul-ca.pem
      - ./target_config/consul-dc1-agent-2/config.json:/consul/config/config.json
      - ./target_certs/consul-dc1-agent-2/client.pem:/etc/ssl/certs/client.pem
      - ./target_certs/consul-dc1-agent-2/client-key.pem:/home/consul/ssl/private/client-key.pem
      - ./target_certs/consul-dc1/cli.pem:/etc/ssl/certs/cli.pem
      - ./target_certs/consul-dc1/cli-key.pem:/home/consul/ssl/private/cli-key.pem
    networks:
      consul-poc: {}

  consul-dc2-agent-1:
    <<: *consul-base
    hostname: consul-dc2-agent-1
    volumes:
      - ./config/acl/acl.json:/consul/config/acl.json
      - ./config/consul/checks.json:/consul/config/checks.json
      - ./config/consul/client_tls.json:/consul/config/tls.json
      - ./config/ssl/ca.pem:/etc/ssl/certs/consul-ca.pem
      - ./target_config/consul-dc2-agent-1/config.json:/consul/config/config.json
      - ./target_certs/consul-dc2-agent-1/client.pem:/etc/ssl/certs/client.pem
      - ./target_certs/consul-dc2-agent-1/client-key.pem:/home/consul/ssl/private/client-key.pem
      - ./target_certs/consul-dc2/cli.pem:/etc/ssl/certs/cli.pem
      - ./target_certs/consul-dc2/cli-key.pem:/home/consul/ssl/private/cli-key.pem
    networks:
      consul-poc: {}

  consul-dc3-agent-1:
    <<: *consul-base
    hostname: consul-dc3-agent-1
    volumes:
      - ./config/acl/acl.json:/consul/config/acl.json
      - ./config/consul/checks.json:/consul/config/checks.json
      - ./config/consul/client_tls.json:/consul/config/tls.json
      - ./config/ssl/ca.pem:/etc/ssl/certs/consul-ca.pem
      - ./target_config/consul-dc3-agent-1/config.json:/consul/config/config.json
      - ./target_certs/consul-dc3-agent-1/client.pem:/etc/ssl/certs/client.pem
      - ./target_certs/consul-dc3-agent-1/client-key.pem:/home/consul/ssl/private/client-key.pem
      - ./target_certs/consul-dc3/cli.pem:/etc/ssl/certs/cli.pem
      - ./target_certs/consul-dc3/cli-key.pem:/home/consul/ssl/private/cli-key.pem
    networks:
      consul-poc: {}

  consul-dc1-server-1:
    <<: *consul-base
    hostname: consul-dc1-server-1
    volumes:
      - ./config/acl/acl.json:/consul/config/acl.json
      - ./config/consul/checks.json:/consul/config/checks.json
      - ./config/consul/server_tls.json:/consul/config/tls.json
      - ./config/ssl/ca.pem:/etc/ssl/certs/consul-ca.pem
      - ./target_config/consul-dc1-server-1/config.json:/consul/config/config.json
      - ./target_config/consul-dc1-server-1/master_token.json:/consul/config/master_token.json
      - ./target_certs/consul-dc1-server-1/server.pem:/etc/ssl/certs/server.pem
      - ./target_certs/consul-dc1-server-1/server-key.pem:/home/consul/ssl/private/server-key.pem
      - ./target_certs/consul-dc1/cli.pem:/etc/ssl/certs/cli.pem
      - ./target_certs/consul-dc1/cli-key.pem:/home/consul/ssl/private/cli-key.pem
    networks:
      consul-poc:
        ipv4_address: 172.16.0.11

  consul-dc1-server-2:
    <<: *consul-base
    hostname: consul-dc1-server-2
    volumes:
      - ./config/acl/acl.json:/consul/config/acl.json
      - ./config/consul/checks.json:/consul/config/checks.json
      - ./config/consul/server_tls.json:/consul/config/tls.json
      - ./config/ssl/ca.pem:/etc/ssl/certs/consul-ca.pem
      - ./target_config/consul-dc1-server-2/config.json:/consul/config/config.json
      - ./target_config/consul-dc1-server-2/master_token.json:/consul/config/master_token.json
      - ./target_certs/consul-dc1-server-2/server.pem:/etc/ssl/certs/server.pem
      - ./target_certs/consul-dc1-server-2/server-key.pem:/home/consul/ssl/private/server-key.pem
      - ./target_certs/consul-dc1/cli.pem:/etc/ssl/certs/cli.pem
      - ./target_certs/consul-dc1/cli-key.pem:/home/consul/ssl/private/cli-key.pem
    networks:
      consul-poc:
        ipv4_address: 172.16.0.12

  consul-dc1-server-3:
    <<: *consul-base
    hostname: consul-dc1-server-3
    ports:
      - "18400:8400"
      - "18500:8500"
      - "18501:8501"
      - "18600:8600"
      - "18600:8600/udp"
    volumes:
      - ./config/acl/acl.json:/consul/config/acl.json
      - ./config/consul/checks.json:/consul/config/checks.json
      - ./config/consul/server_tls.json:/consul/config/tls.json
      - ./config/ssl/ca.pem:/etc/ssl/certs/consul-ca.pem
      - ./target_config/consul-dc1-server-3/config.json:/consul/config/config.json
      - ./target_config/consul-dc1-server-3/master_token.json:/consul/config/master_token.json
      - ./target_certs/consul-dc1-server-3/server.pem:/etc/ssl/certs/server.pem
      - ./target_certs/consul-dc1-server-3/server-key.pem:/home/consul/ssl/private/server-key.pem
      - ./target_certs/consul-dc1/cli.pem:/etc/ssl/certs/cli.pem
      - ./target_certs/consul-dc1/cli-key.pem:/home/consul/ssl/private/cli-key.pem
    networks:
      consul-poc:
        ipv4_address: 172.16.0.13

  consul-dc2-server-1:
    <<: *consul-base
    hostname: consul-dc2-server-1
    volumes:
      - ./config/acl/acl.json:/consul/config/acl.json
      - ./config/consul/checks.json:/consul/config/checks.json
      - ./config/consul/server_tls.json:/consul/config/tls.json
      - ./config/ssl/ca.pem:/etc/ssl/certs/consul-ca.pem
      - ./target_config/consul-dc2-server-1/config.json:/consul/config/config.json
      - ./target_certs/consul-dc2-server-1/server.pem:/etc/ssl/certs/server.pem
      - ./target_certs/consul-dc2-server-1/server-key.pem:/home/consul/ssl/private/server-key.pem
      - ./target_certs/consul-dc2/cli.pem:/etc/ssl/certs/cli.pem
      - ./target_certs/consul-dc2/cli-key.pem:/home/consul/ssl/private/cli-key.pem
    networks:
      consul-poc:
        ipv4_address: 172.16.1.11

  consul-dc2-server-2:
    <<: *consul-base
    hostname: consul-dc2-server-2
    volumes:
      - ./config/acl/acl.json:/consul/config/acl.json
      - ./config/consul/checks.json:/consul/config/checks.json
      - ./config/consul/server_tls.json:/consul/config/tls.json
      - ./config/ssl/ca.pem:/etc/ssl/certs/consul-ca.pem
      - ./target_config/consul-dc2-server-2/config.json:/consul/config/config.json
      - ./target_certs/consul-dc2-server-2/server.pem:/etc/ssl/certs/server.pem
      - ./target_certs/consul-dc2-server-2/server-key.pem:/home/consul/ssl/private/server-key.pem
      - ./target_certs/consul-dc2/cli.pem:/etc/ssl/certs/cli.pem
      - ./target_certs/consul-dc2/cli-key.pem:/home/consul/ssl/private/cli-key.pem
    networks:
      consul-poc:
        ipv4_address: 172.16.1.12

  consul-dc2-server-3:
    <<: *consul-base
    hostname: consul-dc2-server-3
    ports:
      - "28400:8400"
      - "28500:8500"
      - "28501:8501"
      - "28600:8600"
      - "28600:8600/udp"
    volumes:
      - ./config/acl/acl.json:/consul/config/acl.json
      - ./config/consul/checks.json:/consul/config/checks.json
      - ./config/consul/server_tls.json:/consul/config/tls.json
      - ./config/ssl/ca.pem:/etc/ssl/certs/consul-ca.pem
      - ./target_config/consul-dc2-server-3/config.json:/consul/config/config.json
      - ./target_certs/consul-dc2-server-3/server.pem:/etc/ssl/certs/server.pem
      - ./target_certs/consul-dc2-server-3/server-key.pem:/home/consul/ssl/private/server-key.pem
      - ./target_certs/consul-dc2/cli.pem:/etc/ssl/certs/cli.pem
      - ./target_certs/consul-dc2/cli-key.pem:/home/consul/ssl/private/cli-key.pem
    networks:
      consul-poc:
        ipv4_address: 172.16.1.13

  consul-dc3-server-1:
    <<: *consul-base
    hostname: consul-dc3-server-1
    volumes:
      - ./config/acl/acl.json:/consul/config/acl.json
      - ./config/consul/checks.json:/consul/config/checks.json
      - ./config/consul/server_tls.json:/consul/config/tls.json
      - ./config/ssl/ca.pem:/etc/ssl/certs/consul-ca.pem
      - ./target_config/consul-dc3-server-1/config.json:/consul/config/config.json
      - ./target_certs/consul-dc3-server-1/server.pem:/etc/ssl/certs/server.pem
      - ./target_certs/consul-dc3-server-1/server-key.pem:/home/consul/ssl/private/server-key.pem
      - ./target_certs/consul-dc3/cli.pem:/etc/ssl/certs/cli.pem
      - ./target_certs/consul-dc3/cli-key.pem:/home/consul/ssl/private/cli-key.pem
    networks:
      consul-poc:
        ipv4_address: 172.16.2.11

  consul-dc3-server-2:
    <<: *consul-base
    hostname: consul-dc3-server-2
    volumes:
      - ./config/acl/acl.json:/consul/config/acl.json
      - ./config/consul/checks.json:/consul/config/checks.json
      - ./config/consul/server_tls.json:/consul/config/tls.json
      - ./config/ssl/ca.pem:/etc/ssl/certs/consul-ca.pem
      - ./target_config/consul-dc3-server-2/config.json:/consul/config/config.json
      - ./target_certs/consul-dc3-server-2/server.pem:/etc/ssl/certs/server.pem
      - ./target_certs/consul-dc3-server-2/server-key.pem:/home/consul/ssl/private/server-key.pem
      - ./target_certs/consul-dc3/cli.pem:/etc/ssl/certs/cli.pem
      - ./target_certs/consul-dc3/cli-key.pem:/home/consul/ssl/private/cli-key.pem
    networks:
      consul-poc:
        ipv4_address: 172.16.2.12

  consul-dc3-server-3:
    <<: *consul-base
    hostname: consul-dc3-server-3
    ports:
      - "38400:8400"
      - "38500:8500"
      - "38501:8501"
      - "38600:8600"
      - "38600:8600/udp"
    volumes:
      - ./config/acl/acl.json:/consul/config/acl.json
      - ./config/consul/checks.json:/consul/config/checks.json
      - ./config/consul/server_tls.json:/consul/config/tls.json
      - ./config/ssl/ca.pem:/etc/ssl/certs/consul-ca.pem
      - ./target_config/consul-dc3-server-3/config.json:/consul/config/config.json
      - ./target_certs/consul-dc3-server-3/server.pem:/etc/ssl/certs/server.pem
      - ./target_certs/consul-dc3-server-3/server-key.pem:/home/consul/ssl/private/server-key.pem
      - ./target_certs/consul-dc3/cli.pem:/etc/ssl/certs/cli.pem
      - ./target_certs/consul-dc3/cli-key.pem:/home/consul/ssl/private/cli-key.pem
    networks:
      consul-poc:
        ipv4_address: 172.16.2.13

networks:
  consul-poc:
    ipam:
      config:
        - subnet: 172.16.0.0/22