version: '3.4'

x-consul-base: &consul-base
  image: consul:latest
  command: "agent -data-dir /consul/config"

services:
  consul-dc1-agent-1:
    <<: *consul-base
    hostname: consul-dc1-agent-1
    volumes:
      - ./consul_client/config/consul-dc1-agent-1/config.json:/consul/config/config.json
      - ./templates/client_tls.json:/consul/config/tls.json
      - ./templates/ca.pem:/etc/ssl/certs/consul-ca.pem
      - ./consul_client/certs/consul-dc1-agent-1/client.pem:/etc/ssl/certs/client.pem
      - ./consul_client/certs/consul-dc1-agent-1/client-key.pem:/home/consul/ssl/private/client-key.pem
    networks:
      consul-poc: {}

  consul-dc1-agent-2:
    <<: *consul-base
    hostname: consul-dc1-agent-2
    volumes:
      - ./consul_client/config/consul-dc1-agent-2/config.json:/consul/config/config.json
      - ./templates/client_tls.json:/consul/config/tls.json
      - ./templates/ca.pem:/etc/ssl/certs/consul-ca.pem
      - ./consul_client/certs/consul-dc1-agent-2/client.pem:/etc/ssl/certs/client.pem
      - ./consul_client/certs/consul-dc1-agent-2/client-key.pem:/home/consul/ssl/private/client-key.pem
    networks:
      consul-poc: {}

  consul-dc2-agent-1:
    <<: *consul-base
    hostname: consul-dc2-agent-1
    volumes:
      - ./consul_client/config/consul-dc2-agent-1/config.json:/consul/config/config.json
      - ./templates/client_tls.json:/consul/config/tls.json
      - ./templates/ca.pem:/etc/ssl/certs/consul-ca.pem
      - ./consul_client/certs/consul-dc2-agent-1/client.pem:/etc/ssl/certs/client.pem
      - ./consul_client/certs/consul-dc2-agent-1/client-key.pem:/home/consul/ssl/private/client-key.pem
    networks:
      consul-poc: {}

  consul-dc3-agent-1:
    <<: *consul-base
    hostname: consul-dc3-agent-1
    volumes:
      - ./consul_client/config/consul-dc3-agent-1/config.json:/consul/config/config.json
      - ./templates/client_tls.json:/consul/config/tls.json
      - ./templates/ca.pem:/etc/ssl/certs/consul-ca.pem
      - ./consul_client/certs/consul-dc3-agent-1/client.pem:/etc/ssl/certs/client.pem
      - ./consul_client/certs/consul-dc3-agent-1/client-key.pem:/home/consul/ssl/private/client-key.pem
    networks:
      consul-poc: {}

  consul-dc1-server-1:
    <<: *consul-base
    hostname: consul-dc1-server-1
    volumes:
      - ./consul_server/config/consul-dc1-server-1/config.json:/consul/config/config.json
      - ./templates/server_tls.json:/consul/config/tls.json
      - ./templates/ca.pem:/etc/ssl/certs/consul-ca.pem
      - ./consul_server/certs/consul-dc1-server-1/server.pem:/etc/ssl/certs/server.pem
      - ./consul_server/certs/consul-dc1-server-1/server-key.pem:/home/consul/ssl/private/server-key.pem
    networks:
      consul-poc:
        ipv4_address: 172.16.0.11

  consul-dc1-server-2:
    <<: *consul-base
    hostname: consul-dc1-server-2
    volumes:
      - ./consul_server/config/consul-dc1-server-2/config.json:/consul/config/config.json
      - ./templates/server_tls.json:/consul/config/tls.json
      - ./templates/ca.pem:/etc/ssl/certs/consul-ca.pem
      - ./consul_server/certs/consul-dc1-server-2/server.pem:/etc/ssl/certs/server.pem
      - ./consul_server/certs/consul-dc1-server-2/server-key.pem:/home/consul/ssl/private/server-key.pem
    networks:
      consul-poc:
        ipv4_address: 172.16.0.12

  consul-dc1-server-3:
    <<: *consul-base
    hostname: consul-dc1-server-3
    ports:
      - "18400:8400"
      - "18500:8500"
      - "18600:8600"
      - "18600:8600/udp"
    volumes:
      - ./consul_server/config/consul-dc1-server-3/config.json:/consul/config/config.json
      - ./templates/server_tls.json:/consul/config/tls.json
      - ./templates/ca.pem:/etc/ssl/certs/consul-ca.pem
      - ./consul_server/certs/consul-dc1-server-3/server.pem:/etc/ssl/certs/server.pem
      - ./consul_server/certs/consul-dc1-server-3/server-key.pem:/home/consul/ssl/private/server-key.pem
    networks:
      consul-poc:
        ipv4_address: 172.16.0.13

  consul-dc2-server-1:
    <<: *consul-base
    hostname: consul-dc2-server-1
    volumes:
      - ./consul_server/config/consul-dc2-server-1/config.json:/consul/config/config.json
      - ./templates/server_tls.json:/consul/config/tls.json
      - ./templates/ca.pem:/etc/ssl/certs/consul-ca.pem
      - ./consul_server/certs/consul-dc2-server-1/server.pem:/etc/ssl/certs/server.pem
      - ./consul_server/certs/consul-dc2-server-1/server-key.pem:/home/consul/ssl/private/server-key.pem
    networks:
      consul-poc:
        ipv4_address: 172.16.1.11

  consul-dc2-server-2:
    <<: *consul-base
    hostname: consul-dc2-server-2
    volumes:
      - ./consul_server/config/consul-dc2-server-2/config.json:/consul/config/config.json
      - ./templates/server_tls.json:/consul/config/tls.json
      - ./templates/ca.pem:/etc/ssl/certs/consul-ca.pem
      - ./consul_server/certs/consul-dc2-server-2/server.pem:/etc/ssl/certs/server.pem
      - ./consul_server/certs/consul-dc2-server-2/server-key.pem:/home/consul/ssl/private/server-key.pem
    networks:
      consul-poc:
        ipv4_address: 172.16.1.12

  consul-dc2-server-3:
    <<: *consul-base
    hostname: consul-dc2-server-3
    ports:
      - "28400:8400"
      - "28500:8500"
      - "28600:8600"
      - "28600:8600/udp"
    volumes:
      - ./consul_server/config/consul-dc2-server-3/config.json:/consul/config/config.json
      - ./templates/server_tls.json:/consul/config/tls.json
      - ./templates/ca.pem:/etc/ssl/certs/consul-ca.pem
      - ./consul_server/certs/consul-dc2-server-3/server.pem:/etc/ssl/certs/server.pem
      - ./consul_server/certs/consul-dc2-server-3/server-key.pem:/home/consul/ssl/private/server-key.pem
    networks:
      consul-poc:
        ipv4_address: 172.16.1.13

  consul-dc3-server-1:
    <<: *consul-base
    hostname: consul-dc3-server-1
    volumes:
      - ./consul_server/config/consul-dc3-server-1/config.json:/consul/config/config.json
      - ./templates/server_tls.json:/consul/config/tls.json
      - ./templates/ca.pem:/etc/ssl/certs/consul-ca.pem
      - ./consul_server/certs/consul-dc3-server-1/server.pem:/etc/ssl/certs/server.pem
      - ./consul_server/certs/consul-dc3-server-1/server-key.pem:/home/consul/ssl/private/server-key.pem
    networks:
      consul-poc:
        ipv4_address: 172.16.2.11

  consul-dc3-server-2:
    <<: *consul-base
    hostname: consul-dc3-server-2
    volumes:
      - ./consul_server/config/consul-dc3-server-2/config.json:/consul/config/config.json
      - ./templates/server_tls.json:/consul/config/tls.json
      - ./templates/ca.pem:/etc/ssl/certs/consul-ca.pem
      - ./consul_server/certs/consul-dc3-server-2/server.pem:/etc/ssl/certs/server.pem
      - ./consul_server/certs/consul-dc3-server-2/server-key.pem:/home/consul/ssl/private/server-key.pem
    networks:
      consul-poc:
        ipv4_address: 172.16.2.12

  consul-dc3-server-3:
    <<: *consul-base
    hostname: consul-dc3-server-3
    ports:
      - "38400:8400"
      - "38500:8500"
      - "38600:8600"
      - "38600:8600/udp"
    volumes:
      - ./consul_server/config/consul-dc3-server-3/config.json:/consul/config/config.json
      - ./templates/server_tls.json:/consul/config/tls.json
      - ./templates/ca.pem:/etc/ssl/certs/consul-ca.pem
      - ./consul_server/certs/consul-dc3-server-3/server.pem:/etc/ssl/certs/server.pem
      - ./consul_server/certs/consul-dc3-server-3/server-key.pem:/home/consul/ssl/private/server-key.pem
    networks:
      consul-poc:
        ipv4_address: 172.16.2.13

networks:
  consul-poc:
    ipam:
      config:
        - subnet: 172.16.0.0/22