version: '3.4'

x-consul-base: &consul-base
  image: consul:latest
  command: "agent -data-dir /consul/config"

services:
  consul-agent-1:
    <<: *consul-base
    hostname: consul-agent-1
    volumes:
      - ./consul_client/config/consul-agent-1/config.json:/consul/config/config.json
    networks:
      consul-demo: {}

  consul-agent-2:
    <<: *consul-base
    hostname: consul-agent-2
    volumes:
      - ./consul_client/config/consul-agent-2/config.json:/consul/config/config.json
    networks:
      consul-demo: {}

  consul-agent-3:
    <<: *consul-base
    hostname: consul-agent-3
    volumes:
      - ./consul_client/config/consul-agent-3/config.json:/consul/config/config.json
    networks:
      consul-demo: {}

  consul-server-1:
    <<: *consul-base
    hostname: consul-server-1
    domainname: consul-server-1.example.com
    volumes:
      - ./consul_server/config/consul-server-1/config.json:/consul/config/config.json
    networks:
      consul-demo:
        ipv4_address: 172.16.0.11

  consul-server-2:
    <<: *consul-base
    hostname: consul-server-2
    volumes:
      - ./consul_server/config/consul-server-2/config.json:/consul/config/config.json
    networks:
      consul-demo:
        ipv4_address: 172.16.0.12

  consul-server-3:
    <<: *consul-base
    hostname: consul-server-3
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    volumes:
    - ./consul_server/config/consul-server-3/config.json:/consul/config/config.json
    networks:
      consul-demo:
        ipv4_address: 172.16.0.13

networks:
  consul-demo:
    ipam:
      config:
        - subnet: 172.16.0.0/24